"use strict";
var a;
a = 10;
a = 'Olá';
var b = 10;
var ct = { id: 0, nome: '', fone: '', email: '', ativo: false };
ct.id = 10;
ct.nome = 'Maria';
ct.fone = '8198746238';
ct.email = "maria@email.com";
ct.ativo = false;
console.log(ct);
