"use strict";
var boletim;
boletim = ['Ana', 9.0, 75];
console.log(boletim);
var estoque;
estoque = ['Feijão', 150];
console.log(estoque);
var participantes = [];
participantes.push(['João', 26]);
participantes.push(['Maria', 22]);
participantes.push(['Pedro', 17]);
console.log(participantes);
